apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sensor-data
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: sensor-data
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: anomaly-alerts
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: anomaly-alerts
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: clean-sensor-data
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: clean-sensor-data
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824